### ISSUE TITLE
[OneVietnam_Sprint1] Thông báo trang xác nhận quên mật khẩu qua mail + trang xác nhận đã đổi mật khẩu thành công đang để tiếng anh. Cần thiết kế lại hai trang này.

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#10]
1. Trang thông báo xác nhận quên mật khẩu qua email cần được thiết kế lại và phải thông báo là "Hãy Kiểm Tra Email Của Bạn Để Đặt Lại Mật Khẩu."
   ![20](https://cloud.githubusercontent.com/assets/11547602/17292457/685365bc-5814-11e6-8c1a-6a9452065bbb.PNG)
2. Trang thông báo xác nhận đã đổi mật khẩu thành công cần được thiết kế lại và phải thông báo là "Đặt Lại Mật Khẩu Thành Công. Nhấn Vào Đây Để Đăng Nhập" + đường link dẫn đến trang đăng nhập + "."
   ![21](https://cloud.githubusercontent.com/assets/11547602/17292474/7ffab742-5814-11e6-91be-f1e6ed54bd3e.PNG)

**Comment by TaiLMSE02457** [comment]
Sao em đã close bug này rồi? Vẫn bị mà
