### ISSUE TITLE
[OneVietnam_Sprint1] Role = "Authenticated user" Lỗi giao diện tên hiển thị màn hình tạo bài post

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#11]
Chú ý: Cỡ chữ và phông chữ phải thống nhất với phông chữ và cỡ chữ của trang web One Vietnam.
Hiện tại chữ "Tiêu đề" đang to hơn các phần khác hay chữ "Địa chỉ liên hệ" không được in đậm như các phần khác.
1. Tên bên trên textfield nhập tiêu đề là "Tiêu đề"
2. Nội dung trong textfield nhập tiêu đề là "Nhập tiêu đề"
3. Tên bên trên selection list chọn loại bài đăng là "Loại bài đăng"
4. Các giá trị chọn trong "Loại bài đăng" là "Nhà ở", "Việc làm", "Cho đồ", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo".
5. Tên bên trên textfield chọn thẻ liên quan là "Thẻ liên quan"
6. Nội dung trong textfield chọn thẻ liên quan là "Chọn hoặc thêm thẻ mới"
7. Tên bên trên textfield để viết mô tả cho bài post là "Mô tả"
8. Nội dung trong textfield mô tả là "Thêm mô tả cho bài đăng"
9. Tên bên trên textfield hiện địa chỉ là 'Địa chỉ liên hệ"
10. Nội dung trong textfield địa chỉ liên hệ khi không lấy được địa chỉ của người dùng là "Địa chỉ của bạn"
11. Mục người dùng thêm ảnh là "Thêm ảnh"
12. Button để đăng bài viết là "Đăng bài"
![33](https://cloud.githubusercontent.com/assets/11547602/17328425/e873dc94-58e7-11e6-99b8-78ab56e69e5c.PNG)
13. Người dùng được chọn một trong hai loại địa chỉ liên hệ tên là "Địa điểm hiện tại của bạn" và "Địa chỉ nhà của bạn".
14. Nội dung của textfield tìm kiếm địa điểm là "Tìm kiếm địa điểm"
![34](https://cloud.githubusercontent.com/assets/11547602/17328558/859687a6-58e8-11e6-8fea-d6202563714c.PNG)
15. Textfield mà yêu cầu người dùng điền thì phải đổi để cùng loại với textfiled của trang đăng nhập và trang đăng kí như hình bên dưới, không để dấu \* (ví dụ như \* Tiêu đề thì bỏ dấu \* đi).
![35](https://cloud.githubusercontent.com/assets/11547602/17329125/69c19d42-58eb-11e6-9d4c-e0eec6dabb3e.PNG)

**Comment by ThamDTH** [comment]
Đã cho các mục label in đậm như nhau
Các phần khác sẽ không fix
Tiêu đề cố ý để to hơn những phần khác --> không fix
Về dấu \* không thể để như là màn hình đăng ký, vì còn có combobox chọn loại bài đăng và địa điểm --> không fix

**Comment by ThamDTH** [comment]
@hutra vào check comment em nhé
