### ISSUE TITLE
[OneVietnam_Sprint1] Lỗi giao diện tên hiển thị tab bài đăng của màn hình timeline

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#13]
Màn hình timeline đang bị lỗi phông chữ.
1. Tab hiện bài đăng phải sửa tên là "Bài Đăng"
![38](https://cloud.githubusercontent.com/assets/11547602/17329987/374b061a-58ef-11e6-8984-377fb7f7b83c.PNG)
2. Drop down list để lọc bài đăng của người dùng cần có các giá trị "Tất cả", "Nhà ở", "Việc làm", "Cho đồ", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo".
![39](https://cloud.githubusercontent.com/assets/11547602/17332112/d0388f5c-58f7-11e6-9546-0c3329250f90.PNG)

**Comment by ThamDTH** [comment]
@hutra đã fix bug này
