### ISSUE TITLE
[OneVietnam_Sprint1] Role = "Guest" - Lỗi thông báo màn hình hiển thị bản đồ

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#15]
1. Khi không có người dùng nào trên web phải thông báo "Hiện tại không có người dùng nào." 
   ![1](https://cloud.githubusercontent.com/assets/11547602/17807956/60659eac-6637-11e6-916f-553d94891001.PNG)
2. Khi không có bài viết nào trên web phải thông báo "Hiện tại không có bài viết nào."
   ![2](https://cloud.githubusercontent.com/assets/11547602/17807962/6800167e-6637-11e6-8287-111cca8bf15a.PNG)
3. Pop up của icon tính năng phải đổi thành "Nhà ở", "Việc làm", "Cho đồ", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo", "Vị trí hiện tại".
   ![3](https://cloud.githubusercontent.com/assets/11547602/17808112/5d60dd60-6638-11e6-9046-ae6e46d98bff.PNG)
4. Pop up của icon hiển thị giới tính phải đổi thành "Nam", "Nữ, "Giới tính khác", "Tất cả người dùng"
   ![1](https://cloud.githubusercontent.com/assets/11547602/17808247/5b562dda-6639-11e6-8e2e-3c805ddc1adb.PNG)

**Comment by hutra** [comment]
@dat3t 
Popup của các icon bên phải màn hình map
Đổi "Bán đồ" thành "Mua bán"
Đổi "Nhờ giúp đỡ" thành "Cần giúp đỡ"
=> Để thống nhất với trang khác và trong database

**Comment by dat3t** [comment]
@hutra  done
