### ISSUE TITLE
[OneVietnam_Sprint1] Role = "Guest" - Nhấn vào xem chi tiết của bài viết bị hiện thông báo "Hiện tại không có người dùng nào!"

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#16]
Khi guest nhấn vào "Xem chi tiết" một bài post lại bị hiện ra thông báo "Hiện không có người dùng nào!" rồi mới hiện ra nội dung của bài post
![1](https://cloud.githubusercontent.com/assets/11547602/17808470/9320efa6-663a-11e6-815d-75e631884342.PNG)

**Comment by hutra** [comment]
@dat3t 
Nhấn vào "Xem chi tiết" một bài post. Bài post chỉ hiện lên khoảng 2 giây, xuất hiện chữ "Please wait..." rồi biến mất.

**Comment by dat3t** [comment]
@hutra done
