### ISSUE TITLE
[OneVietnam_Sprint1] Button tạo bài post chắn mất nội dung cửa sổ chat

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#18]
Button tạo bài post đang chắn mất nội dung của cửa sổ chat
![4](https://cloud.githubusercontent.com/assets/11547602/17813448/9a9b8ed8-6655-11e6-8bb5-379f9537b44e.PNG)

**Comment by hutra** [comment]
@TaiLMSE02457 @tehsaya 
Lỗi này vẫn chưa được sửa
![image](https://cloud.githubusercontent.com/assets/11547602/18035467/bb7c4b74-6d80-11e6-9972-24caa77a02ef.png)

**Comment by TaiLMSE02457** [comment]
Đã chuyển button này lên trên em nhé.
