### ISSUE TITLE
[OneVietnam_Sprint1] Nút xóa ảnh khi tạo bài post mới không hiển thị đúng

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#19]
Thêm ảnh vào bài post, khi ảnh đã được tải lên thì nút để xóa ảnh đó đi sẽ không hiển thị icon xóa ảnh mà hiển thị lỗi.
![1](https://cloud.githubusercontent.com/assets/11547602/17971610/bb3c4cf4-6b05-11e6-950c-e29599ba1bf3.PNG)

**Comment by tehsaya** [comment]
![deleteimage](https://cloud.githubusercontent.com/assets/8698566/18005427/1b783e34-6bc4-11e6-87e9-8f706b126fcd.png)
phệt cái ảnh nào vào OneVietnam/Images nhé
