### ISSUE TITLE
[OneVietnam_Sprint1] Lỗi thông báo trang đặt lại mật khẩu đang để tiếng anh

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#2]
1. Để trống trường "Email" phải thông báo lỗi "Email đang để trống."
2. Để trống trường "Mật khẩu mới" phải thông báo lỗi "Mật khẩu mới đang để trống."
3. Để trống trường "Nhập lại mật khẩu" phải thông báo lỗi "Nhập lại mật khẩu đang để trống."
   ![23](https://cloud.githubusercontent.com/assets/11547602/17293706/1c2c8b66-581c-11e6-9caa-0d8f921f60ed.PNG)
4. Nhập mail không đúng định dạng ở màn hình đăng nhập phải báo lỗi "Sai định dạng email."
   ![24](https://cloud.githubusercontent.com/assets/11547602/17293797/a960c4d4-581c-11e6-8d19-ece38110436e.PNG)
5. Nhập mật khẩu < 6 ký tự hoặc > 100 ký tự phải thông báo lỗi "Nhập mật khẩu mới trong khoảng từ 6 đến 100 ký tự."
   ![25](https://cloud.githubusercontent.com/assets/11547602/17294972/24e22592-5824-11e6-877c-ae45657a1910.PNG)
6. Mật khẩu nhập lần hai không khớp với mật khẩu nhập lần đầu phải báo lỗi "Mật khẩu xác nhận không trùng khớp."
   ![26](https://cloud.githubusercontent.com/assets/11547602/17295097/ae9be16a-5824-11e6-81f8-f41c8377e83a.PNG)

**Comment by tehsaya** [comment]
hay

**Comment by hutra** [comment]
Lỗi này vẫn chưa được sửa. Anh Tài hay Toản chú ý nội dung báo lỗi và giới hạn trên dưới nhé. @tehsaya @TaiLMSE02457 
![image](https://cloud.githubusercontent.com/assets/11547602/18035048/4c2ead56-6d77-11e6-9b3c-58badb0a2ce9.png)

**Comment by hutra** [comment]
![image](https://cloud.githubusercontent.com/assets/11547602/18035060/b575c2a4-6d77-11e6-82c2-561723ba461f.png)
Lỗi "Invalid token" này là do xóa giá trị userID hay giá trị code đi và nhấn reset, chú ý nội dung lỗi đang để tiếng anh.
![image](https://cloud.githubusercontent.com/assets/11547602/18035064/c666b988-6d77-11e6-8327-3e2b7b8937b0.png)

**Comment by TaiLMSE02457** [comment]
fixed
