### ISSUE TITLE
[OneVietnam_Sprint1] Đổi tên hai icon cho người dùng chọn địa điểm của mình trong map

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#20]
Icon hình tam giác hiển thị popup "Vị trí hiện tại", icon hình tròn hiển thị popup "Vị trí của tôi"
=> dễ gây nhầm lẫn cho người dùng. Nên đổi tên icon hình tròn thành "Địa chỉ của tôi".
![1](https://cloud.githubusercontent.com/assets/11547602/17974678/3144e2d4-6b11-11e6-8181-2fe523b266e0.PNG)

**Comment by dat3t** [comment]
@hutra  done
