### ISSUE TITLE
[OneVietnam_Sprint1] Nút xóa bài post

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#21]
Nút xóa bài post dễ gây hiểu lầm cho người dùng thành nút đóng cửa sổ. 
Nên đổi thành icon thùng rác và có thêm một icon đóng cửa sổ để người dùng có thể đóng cửa sổ xem chi tiết bài post.
![1](https://cloud.githubusercontent.com/assets/11547602/17977704/fe27c4a0-6b1c-11e6-922e-4b0a7aca65a4.PNG)

**Comment by tehsaya** [comment]
done

**Comment by hutra** [comment]
@tehsaya 
Khi nhấn xem chi tiết bài post mới chỉ có xóa và sửa bài. Không có nút tắt cửa sổ bài viết cho người dùng
=> Hơi bất tiện.
=> Cần cho thêm nút tắt cửa sổ xem chi tiết bài post

**Comment by tehsaya** [comment]
lúc đầu t cho vào xong mọi người bảo click ra ngoài là tắt đc rồi thì ko
cần nút đóng nữa nên t bỏ đi r

2016-08-29 0:40 GMT+07:00 hutra notifications@github.com:
