### ISSUE TITLE
[OneVietnam_Sprint1] Hiển thị sai tổng số bài post trong timeline

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#22]
1. Trong database đang có 45 bài post. Ngoài bảng tin cũng hiển thị 45 bài post. Nhưng trong phần time line chỉ hiển thị 10 bài post
   ![1](https://cloud.githubusercontent.com/assets/11547602/17978033/4b78f5de-6b1e-11e6-81e1-5c01405374e3.PNG)
   ![2](https://cloud.githubusercontent.com/assets/11547602/17978036/4ff5b0e8-6b1e-11e6-9d18-d2021cd04912.PNG)
2. Chọn drop down list cácloại bài đăng như "Cần giúp đỡ", "Bán đồ" vv ....
   => Không hiển thị ra bài post nào trong các loại này.
   Chọn lại "Tất cả" cũng không hiển thị bài đăng nào
   ![3](https://cloud.githubusercontent.com/assets/11547602/17978185/07478712-6b1f-11e6-8a6b-20d0f5515fcb.PNG)

**Comment by tehsaya** [comment]
xong r nhá

**Comment by hutra** [comment]
![image](https://cloud.githubusercontent.com/assets/11547602/18006091/26387ff6-6bc8-11e6-9cc7-732d0ac6ae7d.png)
Cậu check lại kĩ một lần nữa nhé. Xong thì comment vào đây.

**Comment by ThamDTH** [comment]
@hutra @tehsaya 
đã fix bug này
do đang query theo số lượng hiển thị trên màn hình --> phải query tổng số bài post trong DB
