### ISSUE TITLE
[OneVietnam_Sprint2] Role = "Authenticated user" - Post type của bản đồ, bảng tin, timeline đang không thống nhất thứ tự và tên

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#23]
1. Post type của trường loại bài đăng trong create post có thứ tự và tên đang để lần lượt là "Nhà ở", "Việc làm", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo"
   ![1](https://cloud.githubusercontent.com/assets/11547602/18007500/85689b4a-6bce-11e6-8494-f3752b5158d8.PNG)
2. Post type trong bản đồ có thứ tự và tên đang để lần lượt là "Nhờ giúp đỡ", "Nhà ở", "Việc làm", "Cho đồ/Đổi đồ", "Xách tay", "Bán đồ", "Cảnh báo"

![2](https://cloud.githubusercontent.com/assets/11547602/18007588/e7d49342-6bce-11e6-9bde-f0557d567024.PNG)
3. Post type trong màn hình newsfeed có thứ tự và tên đang để lần lượt là "Tất cả", "Việc làm", "Nhà ở", "Đồ dùng", "Xách tay", "Mua bán", "Cần giúp đỡ"
![3](https://cloud.githubusercontent.com/assets/11547602/18008195/5923145e-6bd1-11e6-91c4-f47941b2e0c1.PNG)
4. Post type trong màn hình timeline có thứ tự và tên đang để lần lượt là "Tất cả", "Việc làm", "Nhà ở", "Đồ dùng", "Xách tay", "Mua bán", "Cần giúp đỡ".
![4](https://cloud.githubusercontent.com/assets/11547602/18009547/fc8ec9c6-6bd6-11e6-9ca3-d080a07a9631.PNG)

====> Để cho thống nhất giữa các màn hình với nhau. Và để dễ tạo data test thì thứ tự và tên các icon sẽ để lần lượt là "Nhà ở", "Việc làm", "Cho đồ", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo".

**Comment by ThamDTH** [comment]
Thống nhất theo thứ tự trong DB

**Comment by hutra** [comment]
Vậy thứ tự và tên các icon theo DB sẽ lần lượt là "Nhà ở", "Việc làm", "Cho đồ", "Xách tay", "Mua bán", "Cần giúp đỡ", "Cảnh báo".

**Comment by ThamDTH** [comment]
@hutra @tehsaya phần timeline đã sửa cho load từ trong DB ra

**Comment by dat3t** [comment]
@hutra  done

**Comment by TaiLMSE02457** [comment]
Chú ý : Thống nhất theo thứ tự của Trà, tuy nhiên mục "Cho đồ" text sẽ vẫn là "Cho đồ / Đổi đồ"

**Comment by hutra** [comment]
@ThamDTH 
Drop down list của timeline và newsfeed các giá trị chọn đang để màu khác nhau.
![image](https://cloud.githubusercontent.com/assets/11547602/18035516/97c353fc-6d81-11e6-8815-1e70ce9667f5.png)
![image](https://cloud.githubusercontent.com/assets/11547602/18035520/b20dfbae-6d81-11e6-9dba-feaeaa2a8691.png)

**Comment by ThamDTH** [comment]
Đã fix lại
