### ISSUE TITLE
[OneVietnam_Sprint2] Nút "Xác minh" trong mục giới thiệu của timeline ko hoạt động

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#24]
Khi nhập số điện thoại và nhấn nút "Xác minh" nhưng không có điều gì xảy ra.
![1](https://cloud.githubusercontent.com/assets/11547602/18010400/89bd3f0a-6bda-11e6-9a14-88eb7c1d7d00.PNG)

**Comment by tehsaya** [comment]
done

**Comment by hutra** [comment]
@tehsaya 
Đợi cả ngày không thấy mã xác nhận gửi về. Chắc có lỗi gì rồi
![image](https://cloud.githubusercontent.com/assets/11547602/18035547/0e49bca0-6d82-11e6-8679-f5b9de1e90b5.png)

**Comment by TaiLMSE02457** [comment]
del bug này đi nhé em. không còn nút xác minh nữa
