### ISSUE TITLE
[OneVietnam_Sprint2] Không hiển thị cách để gửi mã bảo mật

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#25]
Khi bật bảo mật hai lớp và đăng nhập lại thì chưa chọn được cách để gửi mã bảo mật.
![2](https://cloud.githubusercontent.com/assets/11547602/18011197/4401aa06-6bde-11e6-91f0-46a47ea7d97c.PNG)

**Comment by ThamDTH** [comment]
@hutra @tehsaya 
liên quan đến bug #24
