### ISSUE TITLE
[OneVietnam_Sprint2] Không thể bật bảo mật hai lớp khi không có số điện thoại

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#26]
Bảo mật có thể gửi mã code qua mail nên có mail cũng có thể bật bảo mật hai lớp.
![2](https://cloud.githubusercontent.com/assets/11547602/18025150/23c34ba2-6c4a-11e6-8c32-fcecfc9d9840.PNG)

**Comment by ThamDTH** [comment]
@TaiLMSE02457 bảo cần thêm số điện thoại

**Comment by ThamDTH** [comment]
@hutra confirm lại với @TaiLMSE02457
