### ISSUE TITLE
[OneVietnam_Sprint2] Thông báo lỗi màn hình cài đặt của timeline

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#27]
1. Tab cài đặt của màn hình timeline phải tên là "Cài Đặt"
2. Các thông báo lỗi của phần đổi mật khẩu chưa có giới hạn trên
3. Để trống trường "Mật khẩu hiện tại" và nhấn nút "Lưu" phải thông báo lỗi "Mật khẩu hiện tại đang để trống."
4. Để trống trường "Mật khẩu mới" và nhấn nút "Lưu" phải thông báo lỗi "Mật khẩu mới đang để trống."
5. Nhập mật khẩu mới < 6 ký tự hoặc > 100 ký tự phải thông báo lỗi "Nhập mật khẩu mới trong khoảng từ 6 đến 100 ký tự."
6. Mật khẩu nhập lần hai không khớp với mật khẩu nhập lần đầu phải báo lỗi "Mật khẩu xác nhận không trùng khớp."
   ![image](https://cloud.githubusercontent.com/assets/11547602/18025753/894036c6-6c5d-11e6-8f7d-3ce098a22cfb.png)
7. Mật khẩu trong trường "Mật khẩu hiện tại" không trùng khớp phải thông báo lỗi "Mật khẩu hiện tại không chính xác."
   ![image](https://cloud.githubusercontent.com/assets/11547602/18025738/2b5f5f00-6c5d-11e6-843f-874e7bd37bf9.png)

**Comment by ThamDTH** [comment]
@hutra đã fix bug này
