### ISSUE TITLE
[OneVietnam_Sprint2] Filter post trên timeline, hiển thị 2 lần

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#28]
filter bài post trong timeline
Khi lăn chuột, thì hiển thị thêm bài post đó lần nữa
![image](https://cloud.githubusercontent.com/assets/16666820/18026538/9c6fd0dc-6c74-11e6-8207-8ab4b15bb7a9.png)

**Comment by ThamDTH** [comment]
@hutra em theo dõi bug này nhé

**Comment by tehsaya** [comment]
done sir
