### ISSUE TITLE
[OneVietnam_Sprint1] Trang đặt lại mật khẩu các trường đang để tiếng anh. Cần thiết kế lại trang này.

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#3]
1. Tiêu đề trang phải tên là "ĐẶT LẠI MẬT KHẨU"
2. Textfield để người dùng nhập email phải tên là "Email"
3. Textfield để người dùng nhập lại mật khẩu mới phải tên là "Mật khẩu mới"
4. Textfield để kiểm tra mật khẩu lần thứ hai phải tên là "Nhập lại mật khẩu"
5. Button để gửi yêu cầu đặt lại mật khẩu phải tên là "Gửi"
   ![22](https://cloud.githubusercontent.com/assets/11547602/17293207/237a3aa6-5819-11e6-90a4-da460251f410.PNG)

**Comment by tehsaya** [comment]
làm sao resolsed đc hả em?

**Comment by hutra** [comment]
chú khôn lên nhiều r đấy @tehsaya

**Comment by hutra** [comment]
Xem lỗi #2 @tehsaya @TaiLMSE02457
