### ISSUE TITLE
[OneVietnam_Sprint2] Lấy địa chỉ của người dùng đang lấy cả từ tiếng anh

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#30]
Khi get location của người dùng thì đang chứa cả từ tiếng anh 

![image](https://cloud.githubusercontent.com/assets/16666820/18026573/dd9e4c68-6c75-11e6-9a8c-fa769d880482.png)

---> check similar cho tất cả các màn hình get location

**Comment by ThamDTH** [comment]
@hutra em theo dõi bug này nhé

**Comment by dat3t** [comment]
@ThamDTH  @hutra  Cái này là do mình gửi request để lấy 1 JSON từ gg map, t lấy đến tận level tên đường, nên chỗ nào k có tên đường thì nó sẽ để là Unnamed. 
T nghĩ vẫn nên để, vì tên road có thể đc gg update bất cứ lúc nào, nên nếu update thì nó sẽ có tên, với lại để unnamed để ng dùng biết là gg nó k cung cấp tên chỗ đấy, chứ k phải họ k chọn đc địa chỉ chỗ đấy. Nói chung là t cố tình để như vậy, chứ k phải bug đâu. Còn mọi người muốn sửa thì cũng đc, k khó đâu.

**Comment by ThamDTH** [comment]
@dat3t @hutra nếu có unnamed thì remove ra khỏi chuỗi tên đó

**Comment by dat3t** [comment]
@ThamDTH  @hutra  đã fix theo yêu cầu nhé
