### ISSUE TITLE
[OneVietnam_Sprint2] Find users và admin posts trong administration khi enter ra trang search result

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#31]
Trong màn hình Administration, khi nhập tên người dùng, tiêu đề bài post, enter thì ra trang search result

--> Do ảnh hưởng của phần sửa common search của semantic
@TaiLMSE02457 check lại phần này

**Comment by TaiLMSE02457** [comment]
fixed

**Comment by ThamDTH** [comment]
filter post bị lỗi

**Comment by TaiLMSE02457** [comment]
resolved
