### ISSUE TITLE
[OneVietnam_Sprint2] button create post đang hiển thị trên trang map ngay cả khi user chưa login

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#42]
Trên màn hình Map, đang hiển thị button create post ngay cả khi chưa log in

--> Expect là không hiển thị button này trên map, nhìn rối mắt

**Comment by TaiLMSE02457** [comment]
Nhấn create post sẽ redirect đến trang log-in.

**Comment by ThamDTH** [comment]
Trang map đang có quá nhiều icon, không cho thêm icon create post vào
Check cho cả màn hình search

**Comment by ThamDTH** [comment]
đã chuyển lên trên
