### ISSUE TITLE
[OneVietnam_Sprint2] Trang newsfeed, phần bài đăng quản trị, avatar đang bị méo

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#43]
Avatar của người đăng bài đang bị méo, không phải hình tròn

![image](https://cloud.githubusercontent.com/assets/16666820/18028757/927bcf68-6cb0-11e6-9871-e769bbb1d01b.png)

**Comment by tehsaya** [comment]
đợi lúc nào em pull code về xem có bị ko, chắc ai mới sửa code css
