### ISSUE TITLE
[OneVietnam_Sprint2] Trang newsfeed, phần bài đăng quản trị, click vào avatar không redirect sang trang timeline

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#44]
Khi click vào avatar thì không redirect đến trang timeline của người đăng bài đó

![image](https://cloud.githubusercontent.com/assets/16666820/18028762/c89b4632-6cb0-11e6-8038-47a7d5201af4.png)

**Comment by tehsaya** [comment]
done

**Comment by ThamDTH** [comment]
@hutra check lại bug này
