### ISSUE TITLE
[OneVietnam_Sprint2] Trang newsfeed, phần bài đăng quản trị, không click vào tiêu đề bài đăng để xem chi tiết được

### ISSUE THREAD

**Issue by ThamDTH** [FPTTeam/OneVietnamVer2#45]
Hiện tại đang để hyperlink cho từ "bài viết"
expect là để hyperlink cho tiêu đề của bài đăng

![image](https://cloud.githubusercontent.com/assets/16666820/18028772/f953a224-6cb0-11e6-96d5-e4ee8c7310ba.png)

**Comment by tehsaya** [comment]
done

**Comment by ThamDTH** [comment]
@hutra check lại bug này em nhé
