### ISSUE TITLE
[OneVietnam_Sprint2] Role = "Guest" Nhập nội dung vào textfield tìm kiếm địa điểm bị che mất chữ 

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#46]
Kết quả nhảy ra khi tìm kiếm địa điểm che mất chữ người dùng nhập vào
![image](https://cloud.githubusercontent.com/assets/11547602/18028799/7f77ab02-6cb1-11e6-829d-6968de81a8d8.png)

**Comment by dat3t** [comment]
@hutra cái này có thể do semantic bên e. các bên khác chạy bth nhé. e thử kéo về check lại xem
