### ISSUE TITLE
[OneVietnam_Sprint2] Nội dung mail gửi về cho người dùng để lấy lại mật khẩu vẫn để tiếng Anh

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#50]
![image](https://cloud.githubusercontent.com/assets/11547602/18035019/7c2a0bbe-6d76-11e6-9891-0743a1857b3a.png)

**Comment by TaiLMSE02457** [comment]
Fix rồi em nhé.
