### ISSUE TITLE
[OneVietnam_Sprint2] Không xem chi tiết được bài viết mới nhất nữa, chỉ duy nhất một bài viết mới nhất thôi

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#53]
![image](https://cloud.githubusercontent.com/assets/11547602/18035405/dcd4b596-6d7f-11e6-9785-83d2347f2f6e.png)

**Comment by TaiLMSE02457** [comment]
bug này đã xong. E test r closed nhé
