### ISSUE TITLE
[OneVietnam_Sprint1] Thông báo lỗi màn hình đăng kí đang để tiếng anh

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#7]
<Chú ý: Tất cả các thông báo phải có dấu chấm ở cuối câu>
1. Để trống trường "Họ Và Tên" phải báo lỗi "Họ và tên đang để trống."
2. Để trống trường "Email" phải báo lỗi "Email đang để trống."
3. Để trống trường "Mật Khẩu" phải báo lỗi "Mật khẩu đang để trống."
4. Để trống trường "Nhập Lại Mật Khẩu" phải báo lỗi "Nhập lại mật khẩu đang để trống."
5. Để trống trường "Địa Điểm Hiện Tại Của Bạn" phải báo lỗi "Địa điểm hiện tại đang để trống."
![1](https://cloud.githubusercontent.com/assets/11547602/17282829/4615e80c-57d4-11e6-9725-44cae1a9dd8d.PNG)
6. Để trống trường "Địa Điểm Hiện Tại Của Bạn" ở phần "Đăng Nhập Bằng Facebook" phải báo lỗi "Địa điểm hiện tại đang để trống."
![14](https://cloud.githubusercontent.com/assets/11547602/17291118/3f968d32-580c-11e6-91ae-acec8878008c.PNG)
7. Nhập < 2 ký tự vào textfield "Họ Và Tên" phải báo lỗi "Nhập họ và tên trong khoảng từ 2 đến 50 ký tự."
![3](https://cloud.githubusercontent.com/assets/11547602/17282968/a38136e4-57d5-11e6-869e-b0b5b19fe4f6.PNG)
8. Nhập sai định dạng mail vào textfield "Email" phải báo lỗi "Sai định dạng Email."
![4](https://cloud.githubusercontent.com/assets/11547602/17282998/f8a0496c-57d5-11e6-965b-f68487215d29.PNG)
9. Nhập < 6 ký tự hoặc > 100 ký tự vào textfield "Mật Khẩu" phải báo lỗi "Nhập mật khẩu trong khoảng từ 6 đến 100 ký tự."
![5](https://cloud.githubusercontent.com/assets/11547602/17283038/6893f3fe-57d6-11e6-91c9-e00e3dc91487.PNG)
10. Textfield "Nhập Lại Mật Khẩu" không khớp với textfield "Mật Khẩu" phải báo lỗi "Mật khẩu xác nhận không trùng khớp."
![6](https://cloud.githubusercontent.com/assets/11547602/17283108/f9d080ee-57d6-11e6-8bb9-c3edf218cc25.PNG)
11. "Họ Và Tên" không để unique nên sẽ không có thông báo lỗi nữa.
![7](https://cloud.githubusercontent.com/assets/11547602/17283229/5c264426-57d8-11e6-89e3-24e234b2dfeb.PNG)
12. Khi nhập email đã được sử dụng trong textfield "Email" phải báo lỗi "Email" + chuỗi kí tự người dùng đã nhập vào textfield "Email" +  "đã được sử dụng."
![8](https://cloud.githubusercontent.com/assets/11547602/17283273/bc7a3490-57d8-11e6-82ea-1d31fbbee267.PNG)
13. Chưa có báo lỗi khi nhập email quá dài. Email phải được giới hạn <= 40 kí tự. Người dùng nhập > 40 kí tự báo lỗi "Nhập Email dưới 40 ký tự."

**Comment by hutra** [comment]
@TaiLMSE02457 
1. Nhập sai định dạng email và nhấn đăng kí vẫn để báo lỗi tiếng anh.
![image](https://cloud.githubusercontent.com/assets/11547602/18035121/fe61631e-6d78-11e6-8601-9af9224486a0.png)
2. Chưa giới hạn mật khẩu từ 6 - 100 kí tự trong màn hình đăng ký
![image](https://cloud.githubusercontent.com/assets/11547602/18035137/573872b6-6d79-11e6-825b-6501e37db29b.png)
3. Mật khẩu xác nhận vẫn để thông báo uppercase hết các kí tự đầu.
![image](https://cloud.githubusercontent.com/assets/11547602/18035145/810cbaf2-6d79-11e6-97f3-7f16f864fb2f.png)
4. Chưa có giới hạn độ dài của mail <= 40 kí tự

**Comment by TaiLMSE02457** [comment]
fixed
