### ISSUE TITLE
[OneVietnam_Sprint1] Thông báo trang xác nhận tài khoản email + trang xác nhận email thành công đang để tiếng anh. Cần thiết kế lại hai trang này.

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#8]
Chú ý: Cuối tất cả các thông báo phải có dấu chấm
1. Trang thông báo người dùng cần xác nhận tài khoản cần được thiết kế lại và phải thông báo là "Bạn cần xác nhận tài khoản qua Email trước khi đăng nhập."
![9](https://cloud.githubusercontent.com/assets/11547602/17283346/8c93279a-57d9-11e6-85a1-a997cc098527.PNG)
2. Trang thông báo xác nhận tài khoản email thành công cần được thiết kế lại và phải thông báo là "Xác nhận Email thành công. Nhấn vào đây để đăng nhập" + đường link dẫn đến trang đăng nhập + "."
![10](https://cloud.githubusercontent.com/assets/11547602/17283500/706fe24a-57db-11e6-9fb1-31da24e2b8c7.PNG)

**Comment by TaiLMSE02457** [comment]
Đã fix
