### ISSUE TITLE
[OneVietnam_Sprint1] Thông báo lỗi màn hình đăng nhập đang để tiếng anh

### ISSUE THREAD

**Issue by hutra** [FPTTeam/OneVietnamVer2#9]
1. Để trống trường "Email" phải báo lỗi "Email đang để trống."
2. Để trống trường "Mật Khẩu" phải báo lỗi "Mật khẩu đang để trống."
   ![12](https://cloud.githubusercontent.com/assets/11547602/17290935/2d32dfb6-580b-11e6-9b79-106d135a9502.PNG)
3. Để trống trường "Địa điểm hiện tại của bạn" phải báo lỗi "Địa điểm hiện tại đang để trống."
   ![13](https://cloud.githubusercontent.com/assets/11547602/17291047/d034bd2e-580b-11e6-869a-eaf9846566e5.PNG)
4. Nhập mail không đúng định dạng ở màn hình đăng nhập phải báo lỗi "Sai định dạng Email."
   ![17](https://cloud.githubusercontent.com/assets/11547602/17291592/23f182be-580f-11e6-9e3f-9e043c066fe3.PNG)
5. Mail chưa đăng kí hoặc nhập sai mật khẩu phải báo lỗi "Thông tin đăng nhập không hợp lệ." và phải giống định dạng của những thông báo lỗi khác. Hiện tại lỗi này đang khác định dạng với các lỗi khác.
   ![18](https://cloud.githubusercontent.com/assets/11547602/17291798/33937ef6-5810-11e6-8ed8-0c9ee7b3eb21.PNG)
6. Để trống trường nhập email để lấy lại mật khẩu phải báo lỗi "Email đang để trống."
   ![15](https://cloud.githubusercontent.com/assets/11547602/17291419/f0bde83e-580d-11e6-86e7-c4a1dd5c2050.PNG)
7. Nhập mail không đúng định dạng ở trang nhập mail để lấy lại mật khẩu phải báo lỗi "Sai định dạng Email."
   ![16](https://cloud.githubusercontent.com/assets/11547602/17291535/bafc87ae-580e-11e6-9004-b7ce5774c941.PNG)

**Comment by TaiLMSE02457** [comment]
Đã fix

**Comment by hutra** [comment]
@TaiLMSE02457 
1. Sai định dạng email vẫn báo lỗi tiếng anh
![image](https://cloud.githubusercontent.com/assets/11547602/18035176/58129198-6d7a-11e6-99ae-aad5416f3fdf.png)
